fix: add lint script for plugin evm and fix lint errors
ai16z/eliza pull request #1171
Opened 2024-12-17 10:31 UTC by nicky-ru

# Risks

None

# Background

## What does this PR do?

Improvements:
1. Fixed Chain Name Formatting:
- Object generation sometimes returned the chain name without quotes, causing the transfer action to fail.
- Improved this behavior by ensuring quotes are added in the constraint:
```ts
chains.map((item) => `"${item}"`).join("|")
```
2. Added Linting Script:
- Introduced a linting script to the project and fixed the linting errors.
3. Restored Transfer Action Logic:
- The merge of #965 degraded the transfer action by ignoring the buildTransferDetails() function.
- This function has been reintegrated into the transfer action.

# Documentation changes needed?

My changes do not require a change to the project documentation.

# Testing

## Where should a reviewer start?

- Try initiate a transfer action with on the evm chain of your choice, the agent should correctly pick the chain.

The rest of the changes rely on automated tests.

## Discord username

nikita_zhou

2024-12-17 17:59 UTC, monilpat requested changes
Thanks for doing this please add tests :)

2024-12-18 11:46 UTC, nicky-ru commented
> Thanks for doing this please add a screengrab or test of this working thanks:)

hi @monilpat! 

## Manual testing of token transfer 

(ignore the "the previous tx failed", I forgot to include plugin in the character file the first time):

<img width="685" alt="Screenshot 2024-12-18 at 7 40 06 PM" src="https://github.com/user-attachments/assets/6583b017-427b-4aab-b684-67fcccf04b92" />

transaction on iotexscan: https://testnet.iotexscan.io/tx/619d23aef2d7b0c49b346d0181efabd52aef05af8315a6c33ec689349734188c

<img width="1049" alt="Screenshot 2024-12-18 at 7 40 32 PM" src="https://github.com/user-attachments/assets/adc2c1cc-ca07-41e9-b02a-363318393d5f" />
<img width="953" alt="Screenshot 2024-12-18 at 7 40 58 PM" src="https://github.com/user-attachments/assets/09ba6e4b-095d-422d-b89a-82562b8c34c2" />

--- 

## And linting: 

<img width="953" alt="Screenshot 2024-12-18 at 7 43 29 PM" src="https://github.com/user-attachments/assets/b8c45369-bf08-4193-ae75-fd238f0eeb26" />

2024-12-20 23:34 UTC, odilitime approved these changes

2024-12-21 05:01 UTC, monilpat approved these changes
thanks for adding testing :)

2024-12-21 05:02 UTC, merged