feat(plugin): add ICP token creation support
ai16z/eliza pull request #357
Opened 2024-11-16 12:39 UTC by asDNSk

- Add plugin-icp to enable token creation on Pickpump platform
- Implement createToken functionality for Internet Computer Protocol (ICP)
- Support ICP token standard and specifications
- Enable seamless integration with Pickpump's token creation flow

BREAKING CHANGE: None

2024-11-16 20:05 UTC, lalalune commented
this is fucking rad, will review later

2024-11-18 23:52 UTC, monilpat commented on packages/plugin-icp/src/actions/createToken.ts
> +const createTokenTemplate = `Respond with a JSON markdown block containing only the extracted values. Use null for any values that cannot be determined.
Can we move this into a templates file for readability? Thanks so much!

2024-11-18 23:52 UTC, monilpat commented on packages/plugin-icp/src/actions/createToken.ts
> +        "bn4fo-iyaaa-aaaap-akp6a-cai"
Can this be moved to a constants file?

2024-11-18 23:53 UTC, monilpat commented on packages/plugin-icp/src/actions/createToken.ts
> +        console.log("Response:", response);
We can remove this

2024-11-18 23:54 UTC, monilpat commented on packages/plugin-icp/src/actions/createToken.ts
> +            console.log("Token created successfully:", createTokenResult);
same here

2024-11-18 23:58 UTC, monilpat commented on packages/plugin-icp/src/types.ts
> +export interface ICPConfig {
nit: space

2024-11-18 23:59 UTC, monilpat commented on packages/plugin-icp/src/utils/common/data/json.ts
> +        if (value && typeof value === "object" && value._isPrincipal === true) {
For readability: else if probably more appropriate

2024-11-19 00:00 UTC, monilpat commented on packages/plugin-icp/src/utils/common/data/price.ts
> +    // return value / 1e18;
Can we remove this comment

2024-11-19 00:01 UTC, monilpat commented on packages/plugin-icp/src/utils/hex.ts
> +// hex text -> number array
We could consider moving this to the array utils as they are all related to arrays

2024-11-19 00:08 UTC, monilpat commented on packages/plugin-icp/src/utils/ic/index.ts
> +export const principal2string = (p: Principal): string => p.toText();
Can remove and use util for these

2024-11-19 00:11 UTC, monilpat requested changes
This is some amazing work - thank you for working on this! Added a handful of small nits feel free to address and we are good to go!

2024-11-19 00:26 UTC, monilpat commented
Also feel free to fix the PR Title check, add in a a screen grab of successful token creation, and consider an integration test to simulate the entire token creation flow using mocks or a test canister to ensure the plugin works end-to-end. Also can we update the plugin associated READMEs so it is easier to leverage. Thanks so much! So sorry for all the comments! You are a badass and did some great work here!

2024-11-19 09:20 UTC, asDNSk commented
Thank u for ur review, I will fix the issues. @monilpat

2024-11-19 15:52 UTC, NashAiomos commented
Oh yeah

2024-11-29 11:59 UTC, merged