video generation plugin
ai16z/eliza pull request #394
Opened 2024-11-18 11:07 UTC by dorianjanezic

What does this PR do?
Fixes video generation plugin to properly handle the Luma AI API response and correctly attach generated videos to Discord messages.
What kind of change is this?
Bug fixes (non-breaking change which fixes an issue)
Documentation changes needed?
No documentation changes required.
Testing
Where should a reviewer start?
Start by reviewing the video generation handler in plugin-video-generation

2024-11-18 21:17 UTC, dorianjanezic commented
@lalalune hey, all good with this plugin?

2024-11-18 23:39 UTC, monilpat commented
Thanks for working on this - Please update the PR title :)

2024-11-18 23:39 UTC, monilpat commented on packages/plugin-video-generation/src/index.ts
> +    const API_URL = 'https://api.lumalabs.ai/dream-machine/v1/generations';
Can we move this to a constants file

2024-11-18 23:40 UTC, monilpat commented on packages/plugin-video-generation/src/index.ts
> +
Why do we need to clean it up? Thanks for clarifying!

2024-11-18 23:42 UTC, monilpat commented
Can we add a test for this new plugin? As well as a screengrab of successful video generation? Thanks so much!

2024-11-18 23:44 UTC, monilpat commented on packages/plugin-video-generation/src/index.ts
> +    const API_KEY = runtime.getSetting("LUMA_API_KEY");
Can we update the .env.example file to include the LUMA_API_KEY?

2024-11-18 23:44 UTC, monilpat requested changes
Thanks for working on this! Great feature and implementation! Please address the comments then good to go!

2024-11-19 10:01 UTC, dorianjanezic commented
hey, created constants file and videoGeneration test. 

![Screenshot 2024-11-18 at 11 58 23](https://github.com/user-attachments/assets/8f82cccb-2d8a-41a5-815f-36345f556e92)

2024-11-19 14:36 UTC, merged