Add slack plugin
ai16z/eliza pull request #859
Opened 2024-12-05 14:10 UTC by AIFlowML

# Add Slack Integration for Eliza AI Agent

## Overview
This PR adds a new Slack client integration for the Eliza AI agent, enabling seamless communication between Slack workspaces and the Eliza AI system. The integration includes robust message handling, conversation management, and standalone example scripts for easy testing and deployment.

## Features
- Full Slack bot integration with event handling and message management
- Message deduplication system to prevent duplicate responses
- Thread-aware conversation handling
- Support for attachments and media files
- Conversation summarization capabilities
- Standalone example scripts for testing and development

## Example Scripts
The package includes several standalone scripts in `packages/client-slack/src/examples/`:

1. **standalone-example.ts**
   - Basic bot setup and connection
   - Demonstrates message sending, threading, and image attachments
   - Includes error handling and port management

2. **standalone-summarize.ts**
   - Shows conversation summarization capabilities
   - Demonstrates handling attachments and threaded discussions

3. **standalone-attachment.ts**
   - Comprehensive attachment handling
   - File upload and sharing capabilities

## Setup and Configuration
### 1. Slack App Creation
![Slack App Creation](https://raw.githubusercontent.com/AIFlowML/eliza_aiflow/add-slack-plugin/packages/client-slack/src/examples/sc_01.png)
- Create a new Slack app using the provided manifest
- Configure bot permissions and event subscriptions

### 2. Bot Configuration
![Bot Configuration](https://raw.githubusercontent.com/AIFlowML/eliza_aiflow/add-slack-plugin/packages/client-slack/src/examples/sc_02.png)
- Set up OAuth scopes and bot token
- Configure event subscriptions and interactive components

## Testing Instructions
### Running Example Scripts
1. Set up environment variables in `.env`:
   ```bash
   SLACK_APP_ID=your_app_id
   SLACK_CLIENT_ID=your_client_id
   SLACK_CLIENT_SECRET=your_client_secret
   SLACK_SIGNING_SECRET=your_signing_secret
   SLACK_BOT_TOKEN=xoxb-your-bot-token
   SLACK_VERIFICATION_TOKEN=your_verification_token
   SLACK_CHANNEL_ID=test_channel_id
   ```

2. Run the basic example:
   ```bash
   ts-node packages/client-slack/src/examples/standalone-example.ts
   ```

3. Test summarization:
   ```bash
   ts-node packages/client-slack/src/examples/standalone-summarize.ts
   ```

4. Try attachment handling:
   ```bash
   ts-node packages/client-slack/src/examples/standalone-attachment.ts
   ```

### Verifying Integration
1. Start a new conversation with the bot
2. Test direct mentions and thread replies
3. Try uploading files and requesting summaries
4. Verify message handling in different channel types (DM, public, private)

## Technical Details
- TypeScript-based implementation with full type safety
- Event-driven architecture for message handling
- Built-in error handling and logging
- Configurable message deduplication
- Extensible provider system for easy customization

## Documentation
- Full setup guide in README.md
- Example scripts with inline documentation
- Type definitions for all public APIs
- Environment configuration guide

## Checklist
- [x] TypeScript implementation with full type coverage
- [x] Comprehensive example scripts
- [x] Setup screenshots and documentation
- [x] Error handling and logging
- [x] Message deduplication system
- [x] Thread awareness
- [x] Attachment handling
- [x] Environment validation
- [x] Testing instructions

2024-12-05 17:57 UTC, CREWorx commented
Very useful integration!

2024-12-05 18:16 UTC, sirkitree requested changes
overall this appears to have some really great functionality, looking forward to trying it out further. 

Howver there are some path changes in the /docs/ that you probably did not intend to happen (i've seen this happen in other PRs too). Please double check those as I think you'll want to remove them.

2024-12-05 18:16 UTC, sirkitree commented on docs/api/classes/AgentRuntime.md
These docs changes shouldn't be happening.

2024-12-05 18:16 UTC, sirkitree commented on docs/api/classes/CacheManager.md
Nor should these docs changes be happening.

2024-12-05 18:16 UTC, sirkitree commented on docs/api/classes/DbCacheAdapter.md
here as well.

2024-12-14 10:52 UTC, lalalune commented
Merged on `develop`

2024-12-14 10:54 UTC, merged