chore: improve formatting of .env.example for better readability
ai16z/eliza pull request #897
Opened 2024-12-07 14:05 UTC by guzus

# Relates to:

# Risks

Low

# Background

## What does this PR do?
- Organized the `.env.example` file into clearly defined sections with headers.
- Added comments to describe each configuration variable and its purpose.
- Ensured consistent spacing and alignment across the file for readability.
- Grouped related settings, such as API keys, model configurations, and platform-specific settings, under appropriate headers.
- This update enhances maintainability and makes it easier for contributors to understand and update the file.

No functional changes were made; this commit is purely for structural and visual clarity.

## What kind of change is this?

Improvements

# Documentation changes needed?

My changes do not require a change to the project documentation.

# Testing

## Where should a reviewer start?

## Detailed testing steps

None, automated tests are fine.

## Discord username
uncanny_guzus

2024-12-08 04:49 UTC, monilpat requested changes
Thanks for working on formatting this much needed - please make sure no comments are lost.

2024-12-08 04:49 UTC, monilpat commented on .env.example
> -# if not configured it will be generated and written to runtime.character.settings.secrets.COINBASE_GENERATED_WALLET_ID and runtime.character.settings.secrets.COINBASE_GENERATED_WALLET_HEX_SEED
We want to be careful to not remove any comments here as they are useful

2024-12-08 04:49 UTC, monilpat commented on .env.example
> -# for webhook plugin the uri you want to send the webhook to for dummy ones use https://webhook.site
as well as here

2024-12-08 06:11 UTC, guzus commented
Thank you for the review @monilpat ! I’ve resolved the issue. Could you please take a look when you get a chance?

2024-12-08 20:52 UTC, monilpat commented on .env.example
> -COINBASE_GENERATED_WALLET_HEX_SEED= # not your address but the wallet hex seed from generating a wallet through the plugin and calling export
please keep these comments

2024-12-10 16:40 UTC, guzus commented
@monilpat I have intentionally minimized the changes in this Pull Request to reduce confusion for contributors, given the rapid pace of updates in the repository. The changes primarily focus on formatting and improving readability without altering the existing structure or comments. Thank you!

2024-12-10 17:07 UTC, guzus commented on .env.example
https://github.com/ai16z/eliza/pull/897/files hmm did you check here?

2024-12-10 17:10 UTC, odilitime commented on .env.example
yes

2024-12-11 15:49 UTC, monilpat commented
Looks like there are merge conflicts :)

2024-12-11 16:01 UTC, guzus commented
yeah, this repository is really growing fast... @monilpat can you pls check again?

2024-12-14 22:39 UTC, merged