feat: Config eternalai model from env
ai16z/eliza pull request #927
Opened 2024-12-09 03:55 UTC by genesis-0000

# Risks

Low

# Background

## What does this PR do?

Config eternalai model from env

## What kind of change is this?

More flexible than with env

## Why are we doing this? Any context or related work?

Currently, Eliza supports only OpenAI. However, centralized AI providers limit user control, pose trust issues, and create single points of failure with high costs and restricted access. Decentralized AI offers a more transparent, accessible, and resilient alternative, empowering users with greater autonomy.

Learn more about our decentralized inference AI: https://eternalai.org/api

# Documentation changes needed?

My changes require a change to the project documentation.

# Testing

## Where should a reviewer start?

Reviewers start from .env.example

## Detailed testing steps

Run pnpm start --characters="path/to/your/characters/eternal.character.json"

# Deploy Notes

## Database changes

No change

## Deployment instructions

Change .env by adding more

ETERNALAI_MODEL=#require

2024-12-09 05:06 UTC, monilpat requested changes
Thanks for doing this please address comment then good to go :)

2024-12-09 05:06 UTC, monilpat commented on packages/core/src/models.ts
> +            [ModelClass.LARGE]: settings.ETERNALAI_MODEL,
Can we add these existing values as backups if case nothing is configured?

2024-12-10 02:59 UTC, monilpat approved these changes
LGTM thanks for working on this :)

2024-12-10 05:40 UTC, jkbrooks approved these changes

2024-12-10 05:40 UTC, merged